version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
  - package-ecosystem: "terraform"
    directory: "/infra/terraform"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
